(function(){'use strict';
var dialog=document.getElementById('photoDialog');
if(dialog){document.getElementById('photoOpen').addEventListener('click',function(){dialog.showModal()});document.getElementById('photoClose').addEventListener('click',function(){dialog.close()});dialog.addEventListener('click',function(event){if(event.target===dialog){dialog.close()}})}
var tabs=Array.prototype.slice.call(document.querySelectorAll('.tab'));
function select(tab){tabs.forEach(function(item){var panel=document.getElementById(item.getAttribute('aria-controls'));var on=item===tab;item.setAttribute('aria-selected',on?'true':'false');panel.classList.toggle('active',on)});location.hash=tab.id.replace('tab-','')}
tabs.forEach(function(tab){tab.addEventListener('click',function(){select(tab)})});var initial=document.getElementById('tab-'+location.hash.replace('#',''));if(initial){select(initial)}
var themeButton=document.getElementById('themeBtn'),dark=false;try{dark=localStorage.getItem('ml-application-theme')==='dark'}catch(err){}function applyTheme(){document.documentElement.setAttribute('data-theme',dark?'dark':'light');themeButton.innerHTML=dark?'&#9788;':'&#9789;'}if(themeButton){applyTheme();themeButton.addEventListener('click',function(){dark=!dark;applyTheme();try{localStorage.setItem('ml-application-theme',dark?'dark':'light')}catch(err){}})}
var jobs=Array.prototype.slice.call(document.querySelectorAll('#jobs .job')),note=document.getElementById('filterNote');var filters=document.getElementById('expFilters');if(filters){filters.addEventListener('click',function(event){var button=event.target.closest('.chip');if(!button){return}var tag=button.dataset.tag;Array.prototype.forEach.call(filters.querySelectorAll('.chip'),function(item){item.setAttribute('aria-pressed',item===button?'true':'false')});jobs.forEach(function(job){var visible=tag==='all'||(job.dataset.tags||'').split(' ').indexOf(tag)!==-1;job.classList.toggle('hidden',!visible);if(visible&&tag!=='all'){job.open=true}});note.textContent=tag==='all'?'Showing all roles. Tap a card to expand.':'Showing roles related to '+button.textContent+'.'})})}
})();
